// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    EditModal: typeof import("./src/components/EditModal.vue")["default"];
    MainContent: typeof import("./src/components/MainContent/MainContent.vue")["default"];
    NButton: typeof import("naive-ui")["NButton"];
    NCard: typeof import("naive-ui")["NCard"];
    NCol: typeof import("naive-ui")["NCol"];
    NCollapse: typeof import("naive-ui")["NCollapse"];
    NCollapseItem: typeof import("naive-ui")["NCollapseItem"];
    NCollapseTransition: typeof import("naive-ui")["NCollapseTransition"];
    NDropdown: typeof import("naive-ui")["NDropdown"];
    NewTaskPanel: typeof import("./src/components/NewTaskPanel.vue")["default"];
    NForm: typeof import("naive-ui")["NForm"];
    NFormItem: typeof import("naive-ui")["NFormItem"];
    NIcon: typeof import("naive-ui")["NIcon"];
    NInput: typeof import("naive-ui")["NInput"];
    NLayout: typeof import("naive-ui")["NLayout"];
    NLayoutContent: typeof import("naive-ui")["NLayoutContent"];
    NLayoutHeader: typeof import("naive-ui")["NLayoutHeader"];
    NList: typeof import("naive-ui")["NList"];
    NListItem: typeof import("naive-ui")["NListItem"];
    NModal: typeof import("naive-ui")["NModal"];
    NNotificationProvider: typeof import("naive-ui")["NNotificationProvider"];
    NRow: typeof import("naive-ui")["NRow"];
    NThing: typeof import("naive-ui")["NThing"];
    TaskList: typeof import("./src/components/TaskList/TaskList.vue")["default"];
  }
}
