// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EditModal: typeof import('./src/components/tasks-panel/components/EditModal.vue')['default']
    NewTaskPanel: typeof import('./src/components/tasks-panel/components/NewTaskPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskList: typeof import('./src/components/tasks-panel/components/TaskList.vue')['default']
    TasksPanel: typeof import('./src/components/tasks-panel/TasksPanel.vue')['default']
  }
}
