name: test
on: [push]

jobs:
  golangci-lint:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      - run: sed -i 's/dist\/\*/index.html/' ui/ui.go

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m

  go-test:
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu

    name: "${{ matrix.platform }}"

    runs-on: ${{ matrix.platform }}-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      - run: sed -i 's/dist\/\*/index.html/' ui/ui.go

      - name: Test
        run: make test

  ui-test:
    defaults:
      run:
        shell: bash
        working-directory: ui

    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu

    name: "${{ matrix.platform }}"

    runs-on: ${{ matrix.platform }}-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:

      - run: npm run lint
